# Generated by Django 3.1.8 on 2023-11-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190703_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='class_name',
            field=models.CharField(default='Calculus', max_length=255),
        ),
        migrations.AddField(
            model_name='time',
            name='class_name',
            field=models.CharField(default='Calculus', max_length=255),
        ),
    ]
